import type { ReadinessSummary } from './readiness';

export interface ReportUseCase {
  id: string;
  name: string;
  description: string | null;
  purpose: string | null;
  lifecycle: string;
  riskTier: string;
  createdAt: string;
}

export interface ReportAssessment {
  tier: string;
  rationale: string;
  createdAt: string;
}

export interface ReportControl {
  framework: string;
  code: string;
  title: string;
  status: string;
  evidenceCount: number;
  cleanEvidenceCount: number;
}

export interface ReportApproval {
  decision: string;
  comment: string | null;
  approver: string | null;
  decidedAt: string | null;
}

export interface ReadinessReport {
  org: string;
  generatedAt: string;
  useCase: ReportUseCase;
  assessment: ReportAssessment | null;
  readiness: ReadinessSummary;
  controls: ReportControl[];
  approvals: ReportApproval[];
}

/** Escape pipe characters so user content doesn't break Markdown tables. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/**
 * Render a deterministic, audit-ready "EU AI Act Readiness Report" in Markdown.
 * Pure: all data (including `generatedAt`) is passed in, so the output is stable
 * and testable. The same content can be wrapped to HTML/PDF downstream.
 */
export function renderReadinessReportMarkdown(report: ReadinessReport): string {
  const out: string[] = [];
  const push = (line = ''): void => {
    out.push(line);
  };

  push('# EU AI Act Readiness Report');
  push();
  push(`**System:** ${report.useCase.name}`);
  push(`**Organization:** ${report.org}`);
  push(`**Generated:** ${report.generatedAt}`);
  push(`**Use case ID:** \`${report.useCase.id}\``);
  push(`**Lifecycle:** ${report.useCase.lifecycle}`);
  push();
  push(
    '> AI-assisted content in this report is advisory and must be reviewed by a qualified person. This is not legal advice.',
  );
  push();

  push('## 1. System identity');
  push(`- **Name:** ${report.useCase.name}`);
  push(`- **Purpose:** ${report.useCase.purpose ?? 'Not specified'}`);
  push(`- **Description:** ${report.useCase.description ?? 'Not specified'}`);
  push(`- **Registered:** ${report.useCase.createdAt}`);
  push();

  push('## 2. Risk classification');
  push(`- **Risk tier:** ${report.useCase.riskTier}`);
  if (report.assessment) {
    push(`- **Rationale:** ${report.assessment.rationale}`);
    push(`- **Assessed:** ${report.assessment.createdAt}`);
  } else {
    push('- _No risk assessment recorded._');
  }
  push();

  push('## 3. Readiness');
  push(
    `**${report.readiness.readinessPct}% ready** — ${report.readiness.satisfied} of ${report.readiness.required} required controls satisfied.`,
  );
  push();
  push('| Status | Count |');
  push('|---|---|');
  push(`| Implemented | ${report.readiness.byStatus.IMPLEMENTED} |`);
  push(`| In progress | ${report.readiness.byStatus.IN_PROGRESS} |`);
  push(`| Not started | ${report.readiness.byStatus.NOT_STARTED} |`);
  push(`| Not applicable | ${report.readiness.byStatus.NOT_APPLICABLE} |`);
  push();

  push('## 4. Controls');
  if (report.controls.length === 0) {
    push('_No controls mapped._');
  } else {
    push('| Control | Title | Status | Evidence (clean/total) |');
    push('|---|---|---|---|');
    for (const c of report.controls) {
      push(
        `| ${cell(`${c.framework} ${c.code}`)} | ${cell(c.title)} | ${c.status} | ${c.cleanEvidenceCount}/${c.evidenceCount} |`,
      );
    }
  }
  push();

  push('## 5. Gaps');
  if (report.readiness.gaps.length === 0) {
    push('No outstanding gaps.');
  } else {
    for (const gap of report.readiness.gaps) {
      push(`- **${gap.code}** — ${gap.reason}`);
    }
  }
  push();

  push('## 6. Review & approval trail');
  if (report.approvals.length === 0) {
    push('_No approvals recorded._');
  } else {
    push('| Decision | By | When | Comment |');
    push('|---|---|---|---|');
    for (const a of report.approvals) {
      push(
        `| ${a.decision} | ${cell(a.approver ?? '—')} | ${a.decidedAt ?? 'pending'} | ${cell(a.comment ?? '')} |`,
      );
    }
  }
  push();

  push('---');
  push('_Generated by Provenant — system of record for enterprise AI governance._');

  return out.join('\n');
}
